# Generated by Django 4.1.5 on 2023-05-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0004_alter_series_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800, verbose_name='Yorum')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih ve Saat')),
                ('star', models.IntegerField(default=5, verbose_name='Yorum Puanı')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.movie', verbose_name='Film')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.series', verbose_name='Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
