# Generated by Django 4.1.5 on 2023-05-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.movie', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.series', verbose_name='Dizi'),
        ),
    ]
