# Generated by Django 4.1.5 on 2023-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_comment_movie_alter_comment_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug Dizi'),
        ),
    ]
