# Generated by Django 4.1.5 on 2023-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_alter_series_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Başlığı')),
                ('text', models.TextField(blank=True, max_length=250, null=True, verbose_name='Açıklaması')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Sembol')),
            ],
        ),
    ]
