# Generated by Django 4.1.5 on 2023-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_moviemaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moviemaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.moviemaker', verbose_name='İzleme İaretçileri'),
        ),
        migrations.AddField(
            model_name='series',
            name='moviemaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.moviemaker', verbose_name='İzleme İaretçileri'),
        ),
    ]
