# Generated by Django 4.1.5 on 2023-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_movie_moviemaker_series_moviemaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='moviemaker',
        ),
        migrations.RemoveField(
            model_name='series',
            name='moviemaker',
        ),
        migrations.AddField(
            model_name='movie',
            name='moviemaker',
            field=models.ManyToManyField(to='appMy.moviemaker', verbose_name='İzleyici İşaretçileri'),
        ),
        migrations.AddField(
            model_name='series',
            name='moviemaker',
            field=models.ManyToManyField(blank=True, null=True, to='appMy.moviemaker', verbose_name='İzleyici İşaretçileri'),
        ),
    ]
