# Generated by Django 4.1.7 on 2023-05-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0004_category_slug'),
        ('appMy', '0010_remove_movie_moviemaker_remove_series_moviemaker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='series',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='movie',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='appCategory.subcategory', verbose_name='Alt Category'),
        ),
        migrations.AddField(
            model_name='series',
            name='subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='appCategory.subcategory', verbose_name='Alt Category'),
        ),
    ]
