# Generated by Django 4.1.7 on 2023-05-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0004_category_slug'),
        ('appMy', '0011_remove_movie_subcategory_remove_series_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='appCategory.subcategory', verbose_name='Alt Category'),
        ),
        migrations.AlterField(
            model_name='series',
            name='moviemaker',
            field=models.ManyToManyField(blank=True, to='appMy.moviemaker', verbose_name='İzleyici İşaretçileri'),
        ),
        migrations.AlterField(
            model_name='series',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='appCategory.subcategory', verbose_name='Alt Category'),
        ),
    ]
