# Generated by Django 4.1.5 on 2023-05-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_movie_user_series_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Film Adı')),
                ('video', models.FileField(upload_to='SeriesVideo', verbose_name='Film')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Dizi Adı')),
                ('video', models.FileField(upload_to='SeriesVideo', verbose_name='Bölümler')),
                ('sezon', models.CharField(max_length=50, verbose_name='Sezon')),
                ('bölüm', models.CharField(max_length=50, verbose_name='Bölüm')),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ManyToManyField(to='appMy.moviesvideo', verbose_name='Film'),
        ),
        migrations.AddField(
            model_name='series',
            name='video',
            field=models.ManyToManyField(to='appMy.seriesvideo', verbose_name='Bölümler'),
        ),
    ]
