# Generated by Django 4.1.5 on 2023-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0014_moviesvideo_seriesvideo_remove_series_episodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fragman',
            field=models.FileField(null=True, upload_to=None, verbose_name='Frgaman'),
        ),
        migrations.AddField(
            model_name='series',
            name='fragman',
            field=models.FileField(null=True, upload_to=None, verbose_name='Frgaman'),
        ),
    ]
