# Generated by Django 4.1.5 on 2023-06-04 22:16

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0017_series_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.RemoveField(
            model_name='moviesvideo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='series',
            name='video',
        ),
        migrations.RemoveField(
            model_name='seriesvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.moviesvideo', verbose_name='Film'),
        ),
        migrations.AddField(
            model_name='moviesvideo',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AddField(
            model_name='seriesvideo',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.seriesvideo', verbose_name='Dizi'),
        ),
    ]
