# Generated by Django 4.1.5 on 2023-06-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0019_remove_series_url_series_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='url',
            field=models.ManyToManyField(to='appMy.seriesvideo', verbose_name='Dizi'),
        ),
    ]
