# Generated by Django 4.1.5 on 2023-06-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0020_alter_series_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='url',
        ),
    ]
