# Generated by Django 4.1.5 on 2023-06-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0023_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tamamlandi', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
