# Generated by Django 4.1.5 on 2023-06-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0024_bildirim_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bildirim',
            name='tamamlandi',
        ),
    ]
