# Generated by Django 4.1.5 on 2023-06-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0025_remove_bildirim_tamamlandi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bildirim',
        ),
    ]
