# Generated by Django 4.1.5 on 2023-05-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0002_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug Alt Category'),
        ),
    ]
