# Generated by Django 4.1.5 on 2023-05-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProfile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
