# Generated by Django 4.1.5 on 2023-05-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appProfile', '0002_delete_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
