# Generated by Django 4.1.5 on 2023-06-01 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0015_movie_fragman_series_fragman'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=50, verbose_name='Paket Adı')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Profil Fotoğrafı')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=12)),
                ('password', models.CharField(default='-', max_length=50, verbose_name='Password')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appUser.packagetype', verbose_name='Paket Bilgisi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Profil Adı')),
                ('image', models.FileField(upload_to='', verbose_name='Profil Fotoğrafı')),
                ('spectator', models.CharField(choices=[('Genel izleyici', 'Genel izleyici'), ('7+', '7+'), ('13+', '13+'), ('18+', '18+')], max_length=50, null=True, verbose_name='İzleyici Kitlesi')),
                ('language', models.CharField(choices=[('Türkçe', 'Türkçe'), ('English', 'English')], max_length=50, null=True, verbose_name='Dil Seçimi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Mylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.movie', verbose_name='Filmler')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.profil', verbose_name='Profil')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.series', verbose_name='Diziler')),
            ],
        ),
    ]
