# Generated by Django 4.1.5 on 2023-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_alter_packagetype_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Açıklama')),
            ],
        ),
    ]
